name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.07
  - pip
  - pip:
    - jupyter-book
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - sphinx-exercise
    - joblib
    - interpolation
    - sphinx-tojupyter
    - quantecon-book-theme
    - qeds 
    - fiona 
    - geopandas 
    - pyLDAvis 
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost

