name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.9
  - anaconda=2021.11
  - pip
  - pip:
    - jupyter-book>=0.12.1,<0.13
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - sphinx-tojupyter
    - sphinxcontrib-bibtex
    - quantecon-book-theme>=0.3.0,<0.4.0
