name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.07
  - pip
  - pip:
    - git+git://github.com/QuantEcon/quantecon-book-theme@jupyterlab
    - jupyter-book
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - sphinx-exercise
    - joblib
    - interpolation
    - sphinx-tojupyter
    - qeds 
    - fiona 
    - geopandas 
    - pyLDAvis 
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn
  - conda:
    - python-graphviz
